# Generated by Django 5.0 on 2025-09-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
